- hosts: all
  gather_facts: False
  collections:
    - arubanetworks.aoscx
  vars:
    mclag_id: 12
    mclag_vlans:
      - 11
      - 12
    mclag_ports:
      - 1/1/2
      - 1/1/4
    mclag_description: MCLAG_12
  tasks:
    - name: Create VLANs {{mclag_vlans}}
      aoscx_vlan:
        vlan_id: "{{ item }}"
      with_items: "{{ mclag_vlans }}"
    
    - name: Create MCLAG Interface 64 with  3 interfaces.
      aoscx_lag_interface:
        state: create
        name: lag{{ mclag_id }}
        interfaces: "{{ mclag_ports }}"
        multi_chassis: true

    - name: Configure MCLAG L2 Interface 
      aoscx_l2_interface:
        interface: lag{{ mclag_id }}
        vlan_mode: trunk
        vlan_trunks: "{{ mclag_vlans}}"      

    - name: Enable MCLAG Interface
      aoscx_interface:
        name: lag{{ mclag_id }}
        enabled: true
        description: "{{ mclag_description }}"
