- hosts: all
  gather_facts: False
  collections:
    - arubanetworks.aoscx
  vars:
    vsx_role: primary
    vsx_keepalive_int: 1/1/32
    vsx_keepalive_ip_primary: 192.168.1.110
    vsx_keepalive_ip_secondary: 192.168.1.111
    vsx_system_mac: 00:00:00:00:01:11
    vsx_isl_lagid: 1
    vsx_isl_ports:
      - 1/1/10
      - 1/1/11
  tasks:
    - set_fact:
        is_primary: "{{ vsx_role == 'primary' }}"

    - name: Create VSX keepalive L3 interface
      aoscx_l3_interface:
        interface: "{{ vsx_keepalive_int }}"
        description: "VSX KA"
        ipv4: "{{ vsx_keepalive_ip_primary if is_primary else vsx_keepalive_ip_secondary}}/31"

    - name: Create MCLAG Interface 64 with  3 interfaces.
      aoscx_lag_interface:
        state: create
        name: lag{{ vsx_isl_lagid }}
        interfaces: "{{ vsx_isl_ports }}"

    - name: Enable ISL Lag Interface
      aoscx_interface:
        name: lag{{ mclag_id }}
        enabled: true
        description: "VSX ISL"

    - name: Create VSX configuration
      aoscx_vsx:
        device_role: "{{ vsx_role }}"
        isl_port: lag"{{ vsx_isl_lagid }}"
        keepalive_peer_ip: "{{ vsx_keepalive_ip_secondary if is_primary else vsx_keepalive_ip_primary }}"
        keepalive_src_ip:  "{{ vsx_keepalive_ip_primary if is_primary else vsx_keepalive_ip_secondary }}"
        system_mac: "{{ vsx_system_mac }}"
